language: java
jdk: oraclejdk8

notifications:
  slack:
    rooms:
      secure: VtC7N4USvfJvdnowmAFo6qPIuQB2MGMdnliSlTOxiLbVGh40tIHRJNpkUH4Qf9NPbiIi+666BySdL2as+vD8ooF2xn2BWQGHSEIQH49PTCuKM15aXGHpOWjmFg8MZdhXhNsG2zUlIT6HVGutMWLFQp3cjdtXQ9GjyhZe0AcmQJtY0SevY30pKehV6oitwRhh9QqzWtdL1N9ZEcDBlS9ufXA6pI5pl4BX4DDM8685QFOjhNpAi5scL9g1YwvRQ1x8nN7CUtafryumpW0iPpgphHQgkE2I3qiplHHcTkUPG6esokvPuwICjIQ60CXzzomv5ngHUdad1DWp+GavZS4l3J94JRWHeUaOz8A0miZitPuYPCFUEhzjN2X0UA2KjcBx1zB0EY/on2vacOpB/VKE9n5VHBcRd7sib5Tqs5z3WoYel0zNJJLQCUpMMHxlMjL1JjnrsaUqhXcVib1nDDZ1GuL3yBZX4GyTKuQpx+g19pmKeoXIIpVJF92vBjrzpZ0Dce5NBUAjO98Jf+Okuwypo+wVuNkqc9KEJR5YhSYvt1Z41AeQl0rHJFj3X0arFxcxqq8CC4iQA9m7IYvHDqd7GM+pNFyfFsyXJI0s33laM1HHzh7dlJHi8tVVMMmUiVzup+S5zCpXsHc/AWr3df6zktfUk1vV09gAaxS4Y90w8UI=

after_success:
  - bash <(curl -s https://codecov.io/bash)
